package com.operit.hermes;

import android.app.Activity;
import android.webkit.WebView;
import android.webkit.WebSettings;

/** Creates and configures a WebView on the UI thread. */
public class WebViewHelper {
    private static WebView sWebView;
    private static Activity sActivity;

    /** Called from native (worker thread) — posts WebView creation to UI thread. */
    public static void createOnUiThread(Activity activity) {
        sActivity = activity;
        activity.runOnUiThread(new Runnable() {
            @Override
            public void run() {
                createWebView();
            }
        });
    }

    private static void createWebView() {
        android.util.Log.i("HermesOperit", "[Java] Creating WebView on UI thread...");
        WebView wv = new WebView(sActivity);
        wv.getSettings().setJavaScriptEnabled(true);
        wv.getSettings().setDomStorageEnabled(true);
        wv.getSettings().setAllowFileAccess(true);

        // Load the chat HTML from native (stored via JNI)
        String html = getChatHtml();
        wv.loadDataWithBaseURL("file:///android_asset/", html, "text/html", "utf-8", "about:blank");

        sActivity.setContentView(wv);
        sWebView = wv;
        android.util.Log.i("HermesOperit", "[Java] WebView created and set as content");
    }

    /** HTML generated by native and set via JNI. */
    private static String sHtml = "<html><body><h1>Loading...</h1></body></html>";

    public static void setHtml(String html) {
        sHtml = html;
    }

    private static String getChatHtml() {
        return sHtml;
    }
}
